AllCops:
  Exclude:
    - 'db/**/*'
    - '**/*config.rb'
    - 'node_modules/**/*'

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
